-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: ^\.activate\.sh$
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: flake8
    -   id: check-added-large-files
        exclude: ^\.activate\.sh$
    -   id: check-byte-order-marker
    -   id: fix-encoding-pragma
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.3.1
    hooks:
    -   id: reorder-python-imports
        args: [
            '--add-import', 'from __future__ import absolute_import',
            '--add-import', 'from __future__ import unicode_literals',
        ]
